
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Aug 25 22:32:06 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 19;
  public static final int MOD = 21;
  public static final int READ = 4;
  public static final int IDENT = 13;
  public static final int PLUS = 17;
  public static final int RBRACE = 33;
  public static final int RPAREN = 29;
  public static final int EQUAL = 24;
  public static final int CHAR = 34;
  public static final int SEMI = 26;
  public static final int NAMESPACE = 7;
  public static final int TYPE_INT = 14;
  public static final int DECREMENT = 23;
  public static final int RETURN = 5;
  public static final int TYPE_CHAR = 15;
  public static final int TRUE = 10;
  public static final int LBRACE = 32;
  public static final int LBRACKET = 30;
  public static final int LPAREN = 28;
  public static final int RBRACKET = 31;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int DIVIDE = 20;
  public static final int SCOPE = 25;
  public static final int INCREMENT = 22;
  public static final int PROG = 2;
  public static final int MINUS = 18;
  public static final int FALSE = 11;
  public static final int CONST = 8;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int NEW = 9;
  public static final int TYPE_BOOL = 16;
  public static final int VOID = 6;
}

